#pragma once

#ifndef ADMIN_TABLE_MODEL_H
#define ADMIN_TABLE_MODEL_H

#include <QSqlRecord>
#include <QSqlTableModel>

#include "AdminRepository.h"

class DatabaseHandler;

/*!
 * \brief Model behind the admin data browser.
 *
 * Built on QSqlTableModel, so all statements are generated by the Qt SQL driver:
 * the application never assembles SQL. Table/view identifiers come exclusively
 * from sys_admin_tables and are validated against the database catalogue.
 * Edits are applied with OnManualSubmit so that each operation is atomic and
 * errors can be reported with a user-friendly message.
 */
class AdminTableModel final : public QSqlTableModel
{
    Q_OBJECT
public:
    AdminTableModel(QSharedPointer<DatabaseHandler> database, QObject* parent = nullptr);

    bool load(const AdminTableInfo& info);
    [[nodiscard]] const AdminTableInfo& info() const { return m_info; }

    /// Empty record of the editable table (for the "add" form).
    [[nodiscard]] QSqlRecord blankRecord() const;
    /// Primary key value of \a row (the first column in every admin view).
    [[nodiscard]] QVariant keyAt(int row) const;

    bool insert(const QSqlRecord& record, QString* error);
    bool update(int row, const QSqlRecord& record, QString* error);
    bool remove(int row, QString* error);

    QVariant data(const QModelIndex& index, int role = Qt::DisplayRole) const override;

private:
    bool submitOrRevert(QString* error);

    QSharedPointer<DatabaseHandler> m_database;
    AdminTableInfo m_info;
};

#endif // ADMIN_TABLE_MODEL_H
