name: Build Qt + PostgreSQL Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.8.2  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Установка Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}

    # Установка PostgreSQL (libpq)
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev postgresql-client

    # Настройка CMake (если у вас есть CMakeLists.txt)
    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}"  # Путь к Qt (автоматически задаётся в install-qt-action)

    # Сборка
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}
 
